services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XimaOauth2Extended\:
    resource: '../Classes/*'

  Xima\XimaOauth2Extended\EventListener\BackendUserLookup:
    tags:
      - name: event.listener
        identifier: 'oauthBeUserRegistration'

  Xima\XimaOauth2Extended\EventListener\FrontendUserLookup:
    tags:
      - name: event.listener
        identifier: 'oauthFeUserRegistration'

  Xima\XimaOauth2Extended\EventListener\SkipSudoModeRequirement:
    tags:
      - name: event.listener
        identifier: 'oauthSkipSudoModeRequirement'

  Xima\XimaOauth2Extended\Command\SyncBackendUsersCommand:
    tags:
      - name: 'console.command'
        command: 'xima:oauth2:sync-backend-users'
        description: 'Sync backend users from Microsoft Graph (app-only).'
        schedulable: true

  Xima\XimaOauth2Extended\Command\SyncFrontendUsersCommand:
    tags:
      - name: 'console.command'
        command: 'xima:oauth2:sync-frontend-users'
        description: 'Sync frontend users from Microsoft Graph (app-only).'
        schedulable: true
