version: '3'
services:
  oidc-server-mock:
    container_name: "ddev-${DDEV_SITENAME}-oidc-server-mock"
    image: ghcr.io/soluto/oidc-server-mock:latest
    # disable healthcheck as it is broken in latest versions: https://github.com/Soluto/oidc-server-mock/issues/151
    healthcheck:
      disable: true
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      LOGIN_OPTIONS_INLINE: |
        {
          "AllowRememberLogin": false
        }
      LOGOUT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }
      IDENTITY_RESOURCES_INLINE: |
        - Name: avatar
          ClaimTypes:
            - avatar
            - username
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1",
            "Username":"User1",
            "Password":"pwd",
            "Claims": [
              {
                "Type": "name",
                "Value": "Test User",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "test.user@example.org",
                "ValueType": "string"
              },
              {
                "Type": "username",
                "Value": "User1",
                "ValueType": "string"
              },
              {
                "Type": "avatar",
                "Value": "test",
                "ValueType": "string"
              }
            ]
          }
        ]
      CLIENTS_CONFIGURATION_INLINE: |
        [
          {
            "ClientId": "authentik-mock-client",
            "ClientSecrets": ["authentik-mock-client-secret"],
            "Description": "Client for authentik credentials flow",
            "AllowedGrantTypes": ["authorization_code", "password"],
            "RequirePkce": false,
            "AllowAccessTokensViaBrowser": true,
            "RedirectUris": ["https://xima-oauth2-extended.ddev.site/typo3/login?loginProvider=1616569531&oauth2-provider=authentik&login_status=login&commandLI=attempt"],
            "AllowedScopes": ["openid", "profile", "email", "avatar"],
            "IdentityTokenLifetime": 3600,
            "AccessTokenLifetime": 3600,
            "RequireClientSecret": true,
            "AlwaysIncludeUserClaimsInIdToken": true,
          }
        ]
      ASPNET_SERVICES_OPTIONS_INLINE: |
        {
          "ForwardedHeadersOptions": {
            "ForwardedHeaders" : "All"
          }
        }
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: 4011:8080
    labels:
        com.ddev.site-name: ${DDEV_SITENAME}
        com.ddev.approot: ${DDEV_APPROOT}

# go to http://xima-oauth2-extended.ddev.site:4011/
